# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ??
    - train: null
    - prompt: basic
    
retrieve_top_k: 50
rerank_top_k: 50
generation_top_k: 5
pyserini_num_threads: 20
run_name: null
dataset_folder: '/beegfs/scratch/project/calmar/rag-benchmark/V0/datasets/'
index_folder: '/beegfs/scratch/project/calmar/rag-benchmark/V0/indexes/'
runs_folder: '/beegfs/scratch/project/calmar/rag-benchmark/V0/runs/'
experiments_folder: '/beegfs/scratch/project/calmar/rag-benchmark/V0/experiments/'
processing_num_proc: 40
hydra:
    job:
        chdir: False
