# main_config.yaml

defaults:
    - _self_
    - retriever: null
    - reranker: null
    - generator: null
    - dataset: ??
    - train: null
    - prompt: basic
    - reducer: null

trec_file: null
sample_n: null
visualize_attention: null
retrieve_top_k: 49
rerank_top_k: 5
generation_top_k: 5
pyserini_num_threads: 20
run_name: null
dataset_folder: 'datasets/'
index_folder: 'indexes/'
runs_folder: 'runs/'
experiments_folder: 'experiments/'
processing_num_proc: 40
hydra:
    job:
        chdir: False
