train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.ODQAWikiCorpora63tamberALL
            split: "train"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.truthful_qa
            split: "validation"
test:
    doc: null
    query: null